Repository softwareengineering-2024-2/softwareengineering-repo, pull requests merged in 2024-11, with the labels that each got.

#22 feat issue #17: 전역 레이아웃 구성
  app.py
  static/global.css
  static/icons/alarm.svg
  static/icons/backlog.svg
  static/icons/board.svg
  static/icons/calendar.svg
  static/icons/guide.svg
  static/icons/home.svg
  static/icons/lock.svg
  static/icons/milestone.svg
  static/icons/mypage.svg
  static/icons/project.svg
  static/icons/review.svg
  static/icons/sprint.svg
  static/icons/userstory.svg
  static/js/topbar.js
  static/sidebar.css
  static/topbar.css
  templates/backlog.html
  templates/base.html
  templates/board.html
  templates/calendar.html
  templates/guide.html
  templates/milestone.html
  templates/review.html
  templates/sidebar.html
  templates/sprint.html
  templates/temp.html
  templates/topbar.html
  templates/userstory.html
Labels: ✨ Feature

#34 feat #19: 프로덕트 백로그 지정 기능 - 유저스토리/백로그 생성 및 저장 기본 로직
  add_test_data.py
  app.py
  controllers/productbacklog_controller.py
  models/__init__.py
  models/productbacklog_model.py
  models/sprint_model.py
  models/userstory_model.py
  requirements.txt
  templates/productbacklog_back.html
  templates/project_main_back.html
  views/productbacklog_view.py
Labels: ✨ Feature

#35 스프린트 기능 구현
  app.py
  controllers/sprint_controller.py
  models/sprint_model.py
  templates/project_main_back.html
  templates/sprint_back.html
  views/sprint_view.py
Labels: ✨ Feature

#37 #26 feat 로그인 페이지 프로젝트 생성페이지
  static/icons/Google.svg
  static/icons/circle-plus.svg
  static/icons/link.svg
  static/login.css
  static/projects.css
  templates/login.html
  templates/projects.html
Labels: ✨ Feature

#42 feat issue #26 : 프로젝트 생성/참여 모달, 프로필 페이지
  static/icons/chevron-down.svg
  static/js/manage_project.js
  static/js/profile.js
  static/manage_project.css
  static/profile.css
  static/projects.css
  templates/manage_project.html
  templates/profile.html
  templates/projects.html
Labels: ✨ Feature, 🎨 Html&css

#44 feat issue #23, #24 : 유저스토리 기능 구현, not list 기능
  __init__.py
  app.py
  controllers/__init__.py
  controllers/notlist_controller.py
  controllers/userstory_controller.py
  models/not_list_model.py
  models/userstory_model.py
  templates/keyword_check_back.html
  templates/notlist_back.html
  templates/project_main_back.html
  templates/userstory_back.html
  views/__init__.py
  views/notlist_view.py
  views/userstory_view.py
Labels: ✨ Feature

#49 feat issue #36: 백로그/유저스토리 정렬, 백로그 이름 수정
  .gitignore
  controllers/productbacklog_controller.py
  templates/productbacklog_back.html
  views/productbacklog_view.py
Labels: 🐞 BugFix, ✨ Feature

#54 feat issue #36, #49: 프로덕트 백로그 디버그 코드 삭제
  controllers/productbacklog_controller.py
  templates/productbacklog_back.html
  views/productbacklog_view.py
Labels: ✨ Feature

#60 feat issue #53: 로그인 및 프로젝트 관리 기능 프론트 백 연결
  app.py
  controllers/auth.py
  controllers/project_controller.py
  static/login.css
  templates/join_project.html
  templates/login.html
  templates/manage_project.html
  templates/profile.html
  templates/topbar.html
  views/manage_project_view.py
Labels: ✨ Feature

#63 feat issie #46 : 프로덕트백로그 레이아웃 구현
  static/backlog.css
  static/icons/backlog_background.svg
  static/js/backlog.js
  templates/backlog.html
  templates/{{ url_for('static', filename='icons/dotdotdot.svg') }}
  views/productbacklog_view.py
Labels: ✨ Feature, 🎨 Html&css

#66 fix issue #64: profile, 참여 링크, manga_project css 수정
  static/manage_project.css
  static/profile.css
  templates/join_project.html
  templates/manage_project.html
  templates/profile.html
  templates/project_created_back.html
Labels: 🐞 BugFix, 🎨 Html&css

#68 feat issue #61: 프로젝트 관리, 프로덕트 백로그, 스프린트 기능 사이드바 연결
  app.py
  controllers/milestone_controller.py
  controllers/project_controller.py
  static/js/profile.js
  templates/manage_project.html
  templates/milestone_back.html
  templates/profile.html
  templates/project_created.html
  templates/sidebar.html
  templates/topbar.html
  views/manage_project_view.py
  views/milestone_view.py
  views/productbacklog_view.py
  views/project_main_view.py
  views/sprint_view.py
Labels: ✨ Feature

#70 feat issue #65: backlog.js 에러 수정
  static/js/backlog.js
Labels: 🐞 BugFix, ✨ Feature

#75 feat issue #61: 마일스톤 및 프로필 기능 연결
  static/js/milestone.js
  templates/milestone.html
  templates/profile.html
  templates/topbar.html
  views/milestone_view.py
Labels: ✨ Feature, 🔨 Refactor

#86 refactor issue #86: 프로필 역할 선택창 수정 및 유저스토리 오타 수정
  controllers/project_controller.py
  templates/manage_project.html
  templates/profile.html
  templates/userstory.html
Labels: 🔨 Refactor

#88 bugfix issue #87: 로그인 로직 수정, notlist 삭제 모달창 오류 해결, 스프린트에서 백로그 다중 선택 문제 해결
  controllers/auth.py
  templates/sprint.html
  templates/topbar.html
  views/sprint_view.py
  views/userstory_view.py
Labels: 🐞 BugFix, ✨ Feature, 🔨 Refactor

#89 feat issue #31: 마일스톤 및 스프린트 일정 캘린더 연동 기능 구현
  templates/calendar_back.html
  templates/schedule_detail_back.html
  templates/topbar.html
  views/milestone_view.py
  views/sprint_view.py
Labels: ✨ Feature

#95 feat issue #94: 스크럼보드 프론트엔드 구현
  static/js/scrum.js
  static/scrum.css
  templates/scrum.html
Labels: ✨ Feature

#98 feat issue #90: 스프린트 회고 생성, 수정, 조회, 삭제
  app.py
  controllers/retrospect_controller.py
  models/retrospect_model.py
  templates/create_retrospect_back.html
  templates/retrospect_back.html
  templates/sidebar.html
  templates/view_retrospect_back.html
  views/retrospect_view.py
Labels: ✨ Feature

#102 feat issue #90: 스프린트 회고 페이지 수정
  controllers/retrospect_controller.py
  templates/create_retrospect_back.html
  templates/main.html
  templates/retrospect_back.html
  templates/userstory.html
  templates/view_retrospect.html
  views/retrospect_view.py
Labels: 🐞 BugFix, ✨ Feature

#105 feat issue #93: 번다운차트기능구현
  app.py
  controllers/burnup_controller.py
  controllers/project_controller.py
  models/burnup_model.py
  models/sprint_model.py
  static/burnup.css
  static/icons/burnup.svg
  static/js/burnup.js
  templates/burnup.html
  templates/sidebar.html
  views/burnup_view.py
  views/scrum_view.py
  views/sprint_view.py
Labels: ✨ Feature

#107 feat issue #90: 스프린트 회고 작성 시 파일 첨부 로직 추가
  .gitignore
  controllers/productbacklog_controller.py
  controllers/retrospect_controller.py
  drive/drive_init.py
  models/retrospect_model.py
  requirements.txt
  static/js/retrospect.js
  templates/create_retrospect.html
  templates/view_retrospect.html
  views/productbacklog_view.py
  views/retrospect_view.py
Labels: ✨ Feature, 🔨 Refactor

#108 feat issue #90: 파일 다운로드 링크를 저장하도록 기능 수정
  controllers/retrospect_controller.py
  drive/drive_init.py
Labels: ✨ Feature

#111 feat issue #90: 회고 파일 첨부 에러 해결, 파일 삭제 로직 추가 구현
  controllers/retrospect_controller.py
  drive/drive_init.py
  views/retrospect_view.py
Labels: 🐞 BugFix, ✨ Feature

#115 feat issue#96: 캘린더 프론트엔드 구현
  static/calender.css
  static/icons/nav-arrow-left.svg
  static/icons/nav-arrow-right.svg
  static/js/calender.js
  templates/calendar_back.html
  templates/create_schedule_back.html
  views/calendar_view.py
Labels: ✨ Feature

#118 feat 116 : 캘린더 일정 조회 수정 삭제
  controllers/calendar_controller.py
  controllers/todolist_controller.py
  models/calendar_model.py
  static/js/calender.js
  templates/calendar_back.html
  templates/create_schedule_back.html
  views/calendar_view.py
  views/milestone_view.py
  views/sprint_view.py
Labels: ✨ Feature

#120 feat issue #117: pm 설정 제한 기능 구현
  controllers/project_controller.py
  models/project_model.py
  static/profile.css
  templates/profile.html
  views/manage_project_view.py
Labels: ✨ Feature

#121 feat issue #90: 회고 조회 시 파일 이름 보이도록 구현
  drive/drive_init.py
  templates/create_retrospect.html
  templates/view_retrospect.html
  views/retrospect_view.py
Labels: ✨ Feature

#123 html&css #119: htmlcss 캘린더 스크럼 html css 수정
  static/calender.css
  static/js/calender.js
  static/js/main.js
  static/js/manage_project.js
  static/main.css
  static/manage_project.css
  static/scrum.css
  static/sprint.css
  templates/calendar_back.html
  templates/main.html
  templates/manage_project.html
  templates/scrum.html
  templates/sprint.html
Labels: 🎨 Html&css

#125 feat issue #122: 캘린더 마일스톤/스프린트 연동
  controllers/calendar_controller.py
  models/calendar_model.py
  models/sprint_model.py
  views/milestone_view.py
  views/sprint_view.py
Labels: ✨ Feature
